<?php
/**
 * admin/reports_export.php
 * CSV download endpoint for the Reports module.
 * Returns a downloadable CSV of branch performance data
 * for the given date range.
 *
 * GET params: date_from, date_to  (YYYY-MM-DD)
 */
require_once __DIR__ . '/../core/bootstrap.php';
Auth::requireRole('super_admin', '../login.php');

$db = Database::getConnection();

$dateFrom = $_GET['date_from'] ?? date('Y-m-01');
$dateTo   = $_GET['date_to']   ?? date('Y-m-d');

// Sanitise
if (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $dateFrom)) $dateFrom = date('Y-m-01');
if (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $dateTo))   $dateTo   = date('Y-m-d');

$dateToFull = $dateTo . ' 23:59:59';

/* ── Branch Performance ── */
$byBranchStmt = $db->prepare("
    SELECT
        b.branch_name,
        b.branch_code,
        COUNT(o.id)                             AS total_orders,
        SUM(o.current_status = 'Assigned')      AS assigned,
        SUM(o.current_status = 'Accepted')      AS accepted,
        SUM(o.current_status = 'Preparing')     AS preparing,
        SUM(o.current_status = 'Ready')         AS ready,
        SUM(o.current_status = 'Out For Delivery') AS out_for_delivery,
        SUM(o.current_status = 'Delivered')     AS delivered,
        SUM(o.current_status = 'Cancelled')     AS cancelled,
        SUM(o.current_status = 'Returned')      AS returned,
        COALESCE(SUM(o.total_amount), 0)        AS revenue
    FROM branches b
    LEFT JOIN orders o
        ON o.assigned_branch_id = b.id
       AND o.deleted_at IS NULL
       AND o.created_at BETWEEN :from AND :to
    WHERE b.deleted_at IS NULL
    GROUP BY b.id
    ORDER BY total_orders DESC
");
$byBranchStmt->execute([':from' => $dateFrom . ' 00:00:00', ':to' => $dateToFull]);
$rows = $byBranchStmt->fetchAll();

/* ── Set CSV headers ── */
$filename = 'branch-report_' . $dateFrom . '_to_' . $dateTo . '.csv';

header('Content-Type: text/csv; charset=UTF-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Cache-Control: no-cache, no-store, must-revalidate');
header('Pragma: no-cache');
header('Expires: 0');

// UTF-8 BOM for Excel compatibility
echo "\xEF\xBB\xBF";

$out = fopen('php://output', 'w');

// Meta header rows
fputcsv($out, ['Branch Performance Report']);
fputcsv($out, ['Period:', $dateFrom . ' to ' . $dateTo]);
fputcsv($out, ['Generated:', date('Y-m-d H:i:s')]);
fputcsv($out, ['Generated By:', $_SESSION['name'] ?? 'Super Admin']);
fputcsv($out, []);

// Column headers
fputcsv($out, [
    'Branch Name',
    'Branch Code',
    'Total Orders',
    'Assigned',
    'Accepted',
    'Preparing',
    'Ready',
    'Out For Delivery',
    'Delivered',
    'Cancelled',
    'Returned',
    'Total Revenue',
]);

// Data rows
foreach ($rows as $row) {
    fputcsv($out, [
        $row['branch_name'],
        $row['branch_code'],
        $row['total_orders'],
        $row['assigned'],
        $row['accepted'],
        $row['preparing'],
        $row['ready'],
        $row['out_for_delivery'],
        $row['delivered'],
        $row['cancelled'],
        $row['returned'],
        number_format($row['revenue'], 2),
    ]);
}

fclose($out);
exit;
